spring:
  config:
    activate:
      on-profile: local

  profiles:
    url: http://localhost/

  datasource:
    url: ${STOCK_DATASOURCE_LOCAL_URL}
    username: ${STOCK_DATASOURCE_LOCAL_USERNAME}
    password: ${STOCK_DATASOURCE_LOCAL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${STOCK_JPA_OPTION_AUTO}
    show-sql: ${STOCK_JPA_OPTION_ISSHOW}

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${STOCK_KAKAO_LOCAL_CLIENT_ID}
            client-secret: ${STOCK_KAKAO_LOCAL_CLIENT_SECRET}
            redirect-uri: ${STOCK_KAKAO_LOCAL_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - account_email
          google:
            client-id: ${STOCK_GOOGLE_CLIENT_ID}
            client-secret: ${STOCK_GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: google
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

springdoc:
  default-consumes-media-type: ${STOCK_CONSUMES_MEDIATYPE}
  default-produces-media-type: ${STOCK_PRODUCES_MEDIATYPE}
  paths-to-match: ${STOCK_PATH_MATCH}

  swagger-ui:
    path: ${STOCK_SWAGGER_PATH}
    display-request-duration: ${STOCK_SWAGGER_DUTATION}
    groups-order: ${STOCK_SWAGGER_ORDER}
    operations-sorter: ${STOCK_SWAGGER_ISSORTER}
    disable-swagger-default-url: ${STOCK_SWAGGER_DISABLE}
    urls:
      - url: ${STOCK_SWAGGER_LOCAL_URL}
        name: ${STOCK_SWAGGER_NAME}

  api-docs:
    groups:
      enabled: ${STOCK_SWAGGER_ISGROUPS}

server:
  port: 80

property:
  exchange: ${STOCK_EXCHANGE_AUTH_KEY}
  authKey: ${STOCK_EXCHANGE_DATA}
  data: AP01
