spring:
  application:
    name: ${STOCK_APPLICATION_NAME}
  
  datasource:
    driver-class-name: ${STOCK_DATASOURCE_DRIVER}
  
  jpa:
    hibernate:
      ddl-auto: ${STOCK_JPA_OPTION_AUTO}
    show-sql: false

openapi:
  api-key: ${STOCK_OPENAPI_KEY}
  stock-price-info-url: ${STOCK_OPENAPI_STOCK_PRICE_URL}
korea-investment-api:
  api-key: ${STOCK_KIS_API_KEY}
  secret-key: ${STOCK_KIS_SECRET_KEY}
  dev-api-url: ${STOCK_KIS_DEV_API_URL}
  oauth2-token-url: ${STOCK_KIS_OAUTH2_TOKEN_URL} # 접근토큰발급(P)
  inquire-price-url: ${STOCK_KIS_INQUIRE_PRICE_URL} # 주식현재가 시세
  inquire-daily-url: ${STOCK_KIS_INQUIRE_DAILY_URL} # 국내주식 기간별시세
  invest-opinion-url: ${STOCK_KIS_INVEST_OPINION_URL} # 국내주식 종목투자의견
  search-info: ${STOCK_KIS_SEARCH_INFO_URL} # 국내주식 상품기본정보
  volume-rank-url: ${STOCK_KIS_VOLUME_RANK_URL} # 국내주식 거래량순위
  fluctuation-url: ${STOCK_KIS_FLUCTUATION_URL} # 국내주식 등락률 순위
  market-cap-url: ${STOCK_KIS_MARKET_CAP_URL} # 국내주식 시가총액 상위
  hts-top-view-url: ${STOCK_KIS_HTS_TOP_VIEW_URL} # HTS조회상위20종목
  income-statement-url: ${STOCK_KIS_INCOME_STATMENT_URL} # 국내주식 손익계산서
  financial-ratio-url: ${STOCK_KIS_FINANCIAL_RATIO_URL} # 국내주식 재무비율
  profit-ratio-url: ${STOCK_KIS_PROFIT_RATIO_URL} # 국내주식 수익성비율
  stability-ratio-url: ${STOCK_KIS_STABILITY_RATIO_URL} # 국내주식 안정성비율
  growth-ratio-url: ${STOCK_KIS_GROWTH_RATIO_URL} # 국내주식 성장성비율
  dividend-url: ${STOCK_KIS_DIVIDEND_URL} # 국내주식 예탁원정보(배당일정)

jwt:
  secret: ${STOCK_JWT_SECRET}
  expiration: ${STOCK_JWT_EXPIRATION}
  refreshExpiration: ${STOCK_JWT_REFRESH_EXPIRATION}

servlet:
  multipart:
    max-file-size: 10MB        # 단일 파일의 최대 크기
    max-request-size: 10MB     # 요청당 최대 파일 크기
    enabled: true              # 멀티파트 업로드 처리 활성화

cloud:
  aws:
    credentials:
      access-key: ${STOCK_AWS_ACCESS_KEY}
      secret-key: ${STOCK_AWS_SECRET_KEY}
    s3:
      bucket: ${STOCK_AWS_S3_BUCKET}
    region:
      static: ${STOCK_AWS_S3_REGION}
    stack:
      auto: false
