spring:
  config:
    activate:
      on-profile: prod
  profiles:
    url: ${STOCK_PROFILES_PROD_URL}

  datasource:
    url: ${STOCK_DATASOURCE_PROD_URL}
    username: ${STOCK_DATASOURCE_PROD_USERNAME}
    password: ${STOCK_DATASOURCE_PROD_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${STOCK_JPA_OPTION_AUTO}
    show-sql: ${STOCK_JPA_OPTION_ISSHOW} 